image:
  repository: redis/redisinsight
  tag: "2.58"
  pullPolicy: IfNotPresent

service:
  port: 5540

ingress:
  enabled: true
  host: redis-insight.local
  path: /

persistence:
  enabled: true
  size: 1Gi
