{{- if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: pg-config
  namespace: {{ $.Values.namespace }}
data:
  POSTGRES_HOST: "{{ .Values.serviceName }}"
  POSTGRES_PORT: "{{ .Values.port }}"
{{- end }}
