{{- if .Values.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: pg-secret
  namespace: {{ $.Values.namespace }}
type: Opaque
stringData:
  POSTGRES_DB: "{{ .Values.db.name }}"
  POSTGRES_USER: "{{ .Values.db.user }}"
  POSTGRES_PASSWORD: "{{ .Values.db.password }}"
{{- end }}
