apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-env
  namespace: mini-helpdesk
data:
  DATABASE_URL: postgres://appuser:apppass@postgres-service:5432/helpdesk
  DJANGO_DEBUG: "True"
  DJANGO_ALLOWED_HOSTS: "*"
