backend:
  env:
    SECRET_KEY: ref+vault://minihelpdesk/backend#SECRET_KEY
    DJANGO_DEBUG: ref+vault://minihelpdesk/backend#DJANGO_DEBUG

postgres:
  db:
    password: ref+vault://minihelpdesk/postgres#PASSWORD
