backend:
  env:
    SECRET_KEY: ref+vault://minihelpdesk/backend#SECRET_KEY
    DJANGO_DEBUG: ref+vault://minihelpdesk/backend#DJANGO_DEBUG
    RABBITMQ_USERNAME: ref+vault://minihelpdesk/rabbitmq#USERNAME
    RABBITMQ_PASSWORD: ref+vault://minihelpdesk/rabbitmq#PASSWORD
    REDIS_PASSWORD: ref+vault://minihelpdesk/redis#REDIS_PASSWORD


postgres:
  db:
    password: ref+vault://minihelpdesk/postgres#PASSWORD
