apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "redis-insight.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: redis-insight
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis-insight
    spec:
      containers:
        - name: redis-insight
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "redis-insight.fullname" . }}-pvc
