apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis-insight.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: redis-insight
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
